const express=require('express')

const adminController=require('../controller/adminController')
const userController=require('../controller/userController')
const brandController=require('../controller/brandController')
const categoryController=require('../controller/categoryController')
const productController=require('../controller/productController')
const cartController=require('../controller/cartController')
const orderController=require('../controller/oderController')


const multerConfig=require('../Middleware/imageMiddleware')
const jwtMiddleware = require('../Middleware/jwtMiddleware')
const router=new express.Router()

router.post('/registeradmin',adminController.adminRegister)
router.post('/registeruser',userController.userRegister)
router.post('/registeruserotp',userController.userRegisterOtp)
router.post('/login',userController.login)
router.get('/userfind',jwtMiddleware,userController.userFind)
router.put('/user/updateprofile/:id',jwtMiddleware,multerConfig.single('user_image'),userController.updateUser)
router.post('/addproduct',jwtMiddleware,multerConfig.fields([{name:"thumbnail" ,maxCount:1},{name:"image_1" ,maxCount:1},{name:"image_2" ,maxCount:1},{name:"image_3" ,maxCount:1},{name:"image_4" ,maxCount:1}]),productController.addProduct)
router.post('/addbrand',jwtMiddleware,multerConfig.single('image'),brandController.addBrand)
router.post('/addcategory',jwtMiddleware,multerConfig.single('image'),categoryController.addCategory)
router.get('/getallproducts',productController.getAllProducts)
router.get('/getbrands',brandController.getBrand)
router.get('/getcategories',categoryController.getCategories)
router.get('/getoneproduct/:id',productController.getOneProduct)
router.get('/getoneproductedit/:id',jwtMiddleware,productController.getOneProduct)
router.put('/editproduct/:id',jwtMiddleware,multerConfig.single('thumbnail'),productController.editProduct)
router.post('/addtocart',jwtMiddleware,cartController.addToCart)
router.get('/getcart',jwtMiddleware,cartController.getCart)
router.delete('/deleteproduct/:id',jwtMiddleware,productController.deleteProduct)
router.delete('/removefromcart/:id',jwtMiddleware,cartController.removeFromCart)
router.delete('/emptycart',jwtMiddleware,cartController.emptyCart)
router.get('/increasequantity/:id',jwtMiddleware,cartController.increaseQuantity)
router.get('/decreasequantity/:id',jwtMiddleware,cartController.decreaseQuantity)
router.delete('/deleteUser',jwtMiddleware,userController.deletUser)
router.post('/addtoorder',jwtMiddleware,orderController.addToOrders)
router.get('/orderslist',jwtMiddleware,orderController.getOrdersList)
router.get('/orderslistadmin',jwtMiddleware,orderController.getOrdersListAdmin)
router.delete('/deleteorder/:id',jwtMiddleware,orderController.deleteOrder)
router.put('/updateshipping/:id',jwtMiddleware,orderController.updateShipping)


module.exports=router

